# Class 12 Matrix Operations

In [61]:
import numpy as np

## ------------------ MATRIX BASICS ------------------ #

### Define sample matrices

In [62]:
# Define sample matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

C = np.array([[2, 0, -1],
              [3, 4, 5]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix C:\n", C)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Matrix C:
 [[ 2  0 -1]
 [ 3  4  5]]


## ------------------ MATRIX OPERATIONS ------------------ #

### 1. Addition & Subtraction

In [63]:

# 1. Addition & Subtraction
print("\nA + B =\n", A + B)
print("A - B =\n", A - B)


A + B =
 [[ 6  8]
 [10 12]]
A - B =
 [[-4 -4]
 [-4 -4]]


### 2. Scalar Multiplication

In [64]:
# 2. Scalar Multiplication
print("\n2A =\n", 2 * A)



2A =
 [[2 4]
 [6 8]]


### 3. Matrix Multiplication (A x B)

In [65]:
# 3. Matrix Multiplication (A x B)
print("\nA x B =\n", np.dot(A, B))


A x B =
 [[19 22]
 [43 50]]


In [66]:
a = np.array([[1, 2, 3],[0, 1, 2]])
b = np.array([[1, 0],[2, 1], [3, 2]])
multiplication = np.dot(a, b)
print("Matrix of a : \n", a)
print("Matrix of b : \n", b)
print("Multiplicaton a * b : \n", multiplication)

Matrix of a : 
 [[1 2 3]
 [0 1 2]]
Matrix of b : 
 [[1 0]
 [2 1]
 [3 2]]
Multiplicaton a * b : 
 [[14  8]
 [ 8  5]]


In [67]:
c = np.array([[1, 4, 0],[2, 5, 0],[3, 6, 0]])
d = np.array([[0, 0, 0],[0, 0, 0], [7 , 8, 9]])
multiplication = np.dot(c, d)
print("Matrix of c : \n", c)
print("Matrix of d : \n", d)
print("Multiplicaton c * d : \n", multiplication)

Matrix of c : 
 [[1 4 0]
 [2 5 0]
 [3 6 0]]
Matrix of d : 
 [[0 0 0]
 [0 0 0]
 [7 8 9]]
Multiplicaton c * d : 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


#### AB = AC

In [68]:
e = np.array([[1, 4, 0],[2, 5, 0],[3, 6, 0]])
f = np.array([[3, 2, 1],[1, 2, 3], [4 , 5, 6]])
g = np.array([[3, 2, 1],[1, 2, 3], [7 , 8, 9]])
mul1 = np.dot(e, f)
mul2 = np.dot(e, g)
print("Matrix of e : \n", e)
print("Matrix of f : \n", f)
print("Matrix of g : \n", g)
print("Multiplicaton e * f : \n", mul1)
print("Multiplicaton e * g : \n", mul2)

Matrix of e : 
 [[1 4 0]
 [2 5 0]
 [3 6 0]]
Matrix of f : 
 [[3 2 1]
 [1 2 3]
 [4 5 6]]
Matrix of g : 
 [[3 2 1]
 [1 2 3]
 [7 8 9]]
Multiplicaton e * f : 
 [[ 7 10 13]
 [11 14 17]
 [15 18 21]]
Multiplicaton e * g : 
 [[ 7 10 13]
 [11 14 17]
 [15 18 21]]


### 4. Transpose of a Matrix

In [69]:

# 4. Transpose of a Matrix
print("Matrix of A : \n",A)
print("Matrix of C : \n",C)
print("\nTranspose of A:\n", A.T)
print("Transpose of C:\n", C.T)

Matrix of A : 
 [[1 2]
 [3 4]]
Matrix of C : 
 [[ 2  0 -1]
 [ 3  4  5]]

Transpose of A:
 [[1 3]
 [2 4]]
Transpose of C:
 [[ 2  3]
 [ 0  4]
 [-1  5]]


## ------------------ SPECIAL MATRICES ------------------ #

### 5. Identity Matrix

In [70]:
# 5. Identity Matrix
I = np.eye(3, dtype=int)   # 2x2 identity
print("\nIdentity Matrix (I):\n", I)


Identity Matrix (I):
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


### 6. Zero Matrix

In [71]:
# 6. Zero Matrix
Z = np.zeros((3, 3), dtype=int)
print("\nZero Matrix:\n", Z)


Zero Matrix:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


### 7. Diagonal Matrix

In [72]:
# 7. Diagonal Matrix
D = np.diag([1, 2, 3,4])
print("\nDiagonal Matrix:\n", D)


Diagonal Matrix:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


## ------------------ DETERMINANTS ------------------ #

### 8. Determinant of a Matrix

In [73]:
# 8. Determinant of a Matrix
print("Matrix of A : \n",A)
det_A = np.linalg.det(A)
print("\nDeterminant of A:", det_A)

Matrix of A : 
 [[1 2]
 [3 4]]

Determinant of A: -2.0000000000000004


## ------------------ INVERSE ------------------ #

### 9. Inverse of a Matrix (only if determinant ≠ 0)

In [74]:
# 9. Inverse of a Matrix (only if determinant ≠ 0)
print("Matrix of A : \n",A)
if np.linalg.det(A) != 0:
    inv_A = np.linalg.inv(A)
    print("\nInverse of A:\n", inv_A)
else:
    print("\nMatrix A is not invertible")

Matrix of A : 
 [[1 2]
 [3 4]]

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


## ------------------ PROPERTIES ------------------ #

#### 10. Verify (A * A^(-1) = I)

In [75]:
# 10. Verify (A * A^(-1) = I)
print("Matrix of A : \n",A)
print("\nInverse of A:\n", inv_A)
if np.linalg.det(A) != 0:
    print("\nA x A^(-1) =\n", np.dot(A, inv_A))

Matrix of A : 
 [[1 2]
 [3 4]]

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]

A x A^(-1) =
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [76]:
print("Matrix of A : \n",A)
print("\nInverse of A:\n", inv_A)
#Verify 𝐴⋅𝐴^−1 = I
verify = np.dot(A, inv_A)
verify_rounded = np.round(verify) 
print("Check : \n",verify_rounded)

Matrix of A : 
 [[1 2]
 [3 4]]

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Check : 
 [[1. 0.]
 [0. 1.]]


### 11. Symmetric and Skew-Symmetric parts


In [77]:
# 11. Symmetric and Skew-Symmetric parts
print("Matrix of A : \n",A)

sym_A = (A + A.T) / 2
skew_A = (A - A.T) / 2
print("\nSymmetric part of A:\n", sym_A)
print("Skew-Symmetric part of A:\n", skew_A)

Matrix of A : 
 [[1 2]
 [3 4]]

Symmetric part of A:
 [[1.  2.5]
 [2.5 4. ]]
Skew-Symmetric part of A:
 [[ 0.  -0.5]
 [ 0.5  0. ]]


## ------------------ RANK & TRACE ------------------ #

### 12. Trace of a Matrix (sum of diagonal elements)

In [78]:
# 12. Trace of a Matrix (sum of diagonal elements)
print("Matrix of A : \n",A)

print("\nTrace of A:", np.trace(A))

Matrix of A : 
 [[1 2]
 [3 4]]

Trace of A: 5


### 13. Rank of a Matrix

In [79]:
# 13. Rank of a Matrix
print("Matrix of C : \n",C)
print("Rank of C:", np.linalg.matrix_rank(C))

Matrix of C : 
 [[ 2  0 -1]
 [ 3  4  5]]
Rank of C: 2


## ------------------ EIGENVALUES ------------------ #

### 14. Eigenvalues & Eigenvectors

In [80]:
# 14. Eigenvalues & Eigenvectors
print("Matrix of A : \n",A)
eigvals, eigvecs = np.linalg.eig(A)
print("\nEigenvalues of A:", eigvals)
print("Eigenvectors of A:\n", eigvecs)

Matrix of A : 
 [[1 2]
 [3 4]]

Eigenvalues of A: [-0.37228132  5.37228132]
Eigenvectors of A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
