### Numpy Array operations

In [2]:
import numpy as np

#### 1D Array

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing", arr[2:7])
print("With Step", arr[1:8:2])
print("Negative indexing", arr[-3])

Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative indexing 8


#### 2D Array

In [4]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific element", arr_2d[1, 2])
print("Entire row: ", arr_2d[1])
print("Entire row: ", arr_2d[:, 1])

Specific element 6
Entire row:  [4 5 6]
Entire row:  [2 5 8]


## Sorting

In [6]:
# 1d
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array", np.sort(unsorted))

# 2d
arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2D array by column", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2D array by row", np.sort(arr_2d_unsorted, axis=1))

Sorted Array [1 1 2 3 4 5 6 9]
Sorted 2D array by column [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by row [[1 3]
 [1 2]
 [2 3]]


## Filter

In [9]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_numbers = numbers[numbers % 2 == 0]
print("Even numbers", even_numbers)

odd_numbers = numbers[numbers % 2 != 0]
print("Odd Numbers : ", odd_numbers)

Even numbers [ 2  4  6  8 10]
Odd Numbers :  [1 3 5 7 9]


## Filter with mask

In [12]:
mask = numbers > 5
print("Numbers greater than 5 :", numbers[mask])

mask2 = numbers < 3
print("Numbers less than 3 :", numbers[mask2])

Numbers greater than 5 : [ 6  7  8  9 10]
Numbers less than 3 : [1 2]


## Fancy indexing vs np.where()

In [14]:

indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where : ", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where :  [ 6  7  8  9 10]


Codition where work this type like : 

if(numbers > 5 ){
    numbers * 2
}
else {
    numbers
}

In [18]:
condition_array = np.where(numbers > 5, "true",  "false")
print(condition_array)
condition_array2 = np.where(numbers > 5, numbers * 2,  numbers)
print(condition_array2)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']
[ 1  2  3  4  5 12 14 16 18 20]


## Adding,sub,mul,div and removing data

In [27]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print("Combined array: ", combined)

adding = np.add(arr1, arr2)
print("Adding arrays: ", adding)

# or
adding = arr1 + arr2
print("Adding arrays (using +): ", adding)

#Subtraction
sub = np.subtract(arr1, arr2)
print("Subtracting arrays: ", sub)

# or
sub = arr1 - arr2
print("Subtracting arrays (using -): ", sub)

#Multiplication
mul = np.multiply(arr1, arr2)
print("Multiplying arrays: ", mul)

# or
mul = arr1 * arr2
print("Multiplying arrays (using *): ", mul)


#Division
div = np.divide(arr1, arr2)
print("Dividing arrays: ", div)

# or
div = arr1 / arr2
print("Dividing arrays (using /): ", div)


Combined array:  [1 2 3 4 5 6]
Adding arrays:  [5 7 9]
Adding arrays (using +):  [5 7 9]
Subtracting arrays:  [-3 -3 -3]
Subtracting arrays (using -):  [-3 -3 -3]
Multiplying arrays:  [ 4 10 18]
Multiplying arrays (using *):  [ 4 10 18]
Dividing arrays:  [0.25 0.4  0.5 ]
Dividing arrays (using /):  [0.25 0.4  0.5 ]


## array compatibilty

In [31]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("Compatibility shapes : ", a.shape == b.shape)  # True

b = np.array([4, 5, 6, 7])

print("Compatibility shapes : ", a.shape == b.shape)  # False

Compatibility shapes :  True
Compatibility shapes :  False


## Row and Column Add 

In [34]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row)) 
#vstack means vertical stack (always adds rows)
print("Original array: ", original)
print("New row: ", new_row)
print("Array with new row: ", with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
#hstack means horizontal stack (always adds columns)
print("New column: ", new_col)
print("With new column : ", with_new_col)

Original array:  [[1 2]
 [3 4]]
New row:  [[5 6]]
Array with new row:  [[1 2]
 [3 4]
 [5 6]]
New column:  [[7]
 [8]]
With new column :  [[1 2 7]
 [3 4 8]]


## Deleted

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)
# delete element at index 2
print("Array after deletion: ", deleted)

Array after deletion:  [1 2 4 5]
